# version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: my_project_db
    environment:
      MYSQL_DATABASE: IS436_Deliverable
      MYSQL_USER: student  
      MYSQL_PASSWORD: student123  
      MYSQL_ROOT_PASSWORD: rootpassword  
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  db_data:
